### ISSUE TITLE
Set up end-to-end / integration testing via GitHub actions

### ISSUE THREAD

**Issue by oneillkza** [bcgsc/IMPALA#2]
We should set up automated testing by running the complete workflow on a mini-example (including adding some small example data to the repo).

**Comment by Glenn032787** [comment]
I included a small test file in `github_action` branch which is generated from chr22 ASE simulated data and also randomly generated CNV and DMR data. I also included the github action yaml file which runs the workflow, however, github actions prevents it from using the `--use-singularity` command with snakemake when using premade snakemake github action (mentioned in this [issue](https://github.com/snakemake/snakemake-github-action/issues/9)). I will try to either manually install snakemake into github runner or run unit tests.

**Comment by oneillkza** [comment]
Great!

And yeah, manually installing, either directly through apt, or via conda as per [this comment](https://github.com/snakemake/snakemake-github-action/issues/9#issuecomment-832485673), will be the way to go for running snakemake.

When I've run Travis in the past for this kind of testing, it allowed me to just run a few install commands before the test itself.

**Comment by Glenn032787** [comment]
Finally got github actions to run through with no issues! I have created a pull request #3 for adding the small example and adding github actions workflow to the repository. If there is no issues I will merge it to main.
